Repository nayutaco/ptarmigan, pull requests merged in 2019-04, with the labels that each got.

#1268 ln: add `LN_STATUS_CLOSED`
  ln/ln.h
  ptarmd/lnapp_manager.c
  ptarmd/monitoring.c
Labels: bug

#1281 p2p: remove `peer_conn`
  ptarmd/monitoring.c
  ptarmd/p2p.c
  ptarmd/p2p.h
Labels: refactor

#1282 ptarmd: fix to use `lnapp_manager_free_node_ref` properly
  ptarmd/cmd_json.c
  ptarmd/lnapp_cb.c
  ptarmd/lnapp_manager.c
  ptarmd/monitoring.c
  ptarmd/p2p.c
  ptarmd/p2p.h
  ptarmd/ptarmd.c
  ptarmd/ptarmd.h
  ptarmd/tests/testinc_lnapp.cpp
Labels: enhancement

#1289 ln_db: forward dbs is created explicitly
  ln/ln.c
  ln/ln_db.h
  ln/ln_db_lmdb.c
  ln/ln_normalope.c
  ln/ln_update.h
  ln/ln_update_info.c
  ln/tests/test_ln_proto_updateaddhtlc.cpp
  ptarmd/lnapp.c
  ptarmd/lnapp_manager.c
  ptarmd/lnapp_manager.h
  ptarmd/monitoring.c
  ptarmd/ptarmd.c
Labels: enhancement

#1291 ln_normalope: fail to forward of update_add_htlc to closing channels
  ln/ln_normalope.c
Labels: enhancement

#1296 lnapp: remove `mux_channel`
  ptarmd/lnapp.c
  ptarmd/lnapp.h
  ptarmd/monitoring.c
  ptarmd/p2p.c
Labels: bug

#1305 lnapp: retry payment without using JSON-RPC
  install/script/payment.sh
  ln/Makefile
  ln/ln_cb.h
  ln/ln_db.h
  ln/ln_db_lmdb.c
  ln/ln_msg_x_payment.c
  ln/ln_msg_x_payment.h
  ln/ln_normalope.c
  ln/ln_payment.c
  ln/ln_payment.h
  ln/ln_routing.cpp
  ln/ln_routing.h
  ln/tests/test_ln.cpp
  ln/tests/test_ln_proto_acceptchannel.cpp
  ln/tests/test_ln_proto_init.cpp
  ln/tests/test_ln_proto_openchannel.cpp
  ln/tests/test_ln_proto_updateaddhtlc.cpp
  ln/tests/test_ln_proto_updatechannel.cpp
  ln/tests/test_ln_proto_updatefee.cpp
  ptarmcli/conf_cli.c
  ptarmcli/ptarmcli.c
  ptarmd/cmd_json.c
  ptarmd/cmd_json.h
  ptarmd/lnapp.c
  ptarmd/lnapp_cb.c
  ptarmd/lnapp_util.c
  ptarmd/ptarmd.c
  ptarmd/ptarmd.h
  routing/routing.c
Labels: enhancement

#1306 ln_normalope: cancel pending updates
  ln/ln_normalope.c
  ln/ln_normalope.h
  ln/ln_update.c
  ln/ln_update.h
  ln/ln_update_info.c
  ln/ln_update_info.h
  ptarmd/lnapp.c
  ptarmd/lnapp_manager.c
Labels: bug

#1310 ln_normalope: save an inactive channel state
  ln/ln_commit_tx.c
  ln/ln_normalope.c
  ln/ln_update_info.c
  ln/ln_update_info.h
Labels: bug

#1317 ptarmd: refactor
  ptarmd/cmd_json.c
  ptarmd/lnapp.c
  ptarmd/lnapp.h
  ptarmd/monitoring.h
Labels: refactor

#1324 ln_establish: fix to resend `revoke_and_ack`
  ln/ln_derkey_ex.c
  ln/ln_derkey_ex.h
  ln/ln_establish.c
Labels: bug

#1327 ln_commit_tx: refactor
  ln/ln.c
  ln/ln_commit_tx.c
  ln/ln_commit_tx.h
  ln/ln_establish.c
  ln/ln_normalope.c
  ln/tests/test_ln.cpp
  ln/tests/test_ln_htlcflag.cpp
  ln/tests/test_ln_proto_acceptchannel.cpp
  ln/tests/test_ln_proto_openchannel.cpp
  ln/tests/test_ln_proto_updateaddhtlc.cpp
  ln/tests/test_ln_proto_updatefee.cpp
Labels: refactor

#1337 cmd_json: fix to terminate an invoide string a zero
  ptarmd/cmd_json.c
Labels: bug

#1347 ln_close: fix to reconnect during closing negotiation
  ln/ln.c
  ln/ln.h
  ln/ln_close.c
  ln/ln_normalope.c
  ln/ln_routing.cpp
  ptarmd/cmd_json.c
  ptarmd/lnapp.c
  ptarmd/monitoring.c
  ptarmd/ptarmd.c
  ptarmd/ptarmd.h
  showdb/showdb.c
Labels: bug

#1348 lnapp: fix to block normal operation in closing
  ptarmd/lnapp.c
Labels: bug

#1357 ln: fix to support second last unilateral close txs
  ln/ln.c
  ln/ln.h
  ln/ln_commit_tx.c
  ln/ln_db_lmdb.c
  ln/ln_normalope.c
  ln/ln_version.h
Labels: bug

#1363 monitoring: fix to monitor inactive channels frequently
  ptarmd/monitoring.c
Labels: enhancement

#1369 monitoring: fix to unlock a mutex before reconnecting
  ptarmd/monitoring.c
Labels: bug

#1372 lnapp_manager: fix to stop closed channel threads
  ptarmd/lnapp_manager.c
Labels: bug

#1385 ln_db_lmdb: fix to not close dbs
  ln/ln_db_lmdb.c
Labels: bug

#1386 lnapp_util: fix to lock mux_conf outside mux_conf lock
  ptarmd/lnapp_util.c
Labels: bug

#1387 lnapp: fix to not stop threads in `lnapp_send_peer_noise`
  ptarmd/lnapp.c
  ptarmd/lnapp_cb.c
  ptarmd/lnapp_util.c
Labels: bug

#1388 lnapp: add logs
  ptarmd/lnapp.c
Labels: enhancement

#1396 tools: update a script
  tools/git_sync_upstream.sh
Labels: enhancement

#1397 lnapp: skip `check_unspent_short_channel_id`
  ptarmd/lnapp.c
Labels: enhancement

#1402 fundin.py: unlock after error
  install/pay_fundin.py
Labels: bug

#1403 ln_anno: disable to verify sigs of announcements
  ln/ln_anno.c
  ln/tests/test_ln_proto_updatechannel.cpp
Labels: enhancement

#1404 ln_normalope: fix to save channels
  ln/ln_normalope.c
Labels: bug

#1406 routing: log
  ln/ln_routing.cpp
Labels: enhancement

#1409 remove log of secrets
  ln/ln_commit_tx.c
  ln/ln_db_lmdb.c
  ln/ln_derkey.c
  ln/ln_establish.c
  ln/ln_msg_normalope.c
  ln/ln_msg_x_normalope.c
  ln/ln_normalope.c
  ln/ln_onion.c
  ptarmd/monitoring.c
  ptarmd/wallet.c
  utl/utl_str.c
Labels: enhancement

#1411 ln, ptarmd: remove anno logs
  ln/ln_anno.c
  ln/ln_db_lmdb.c
  ptarmd/lnapp_cb.c
Labels: enhancement

#1412 ptarmcli: `PEER NODE_ID` -> `PEER_NODE_ID`
  ptarmcli/ptarmcli.c
Labels: enhancement
